# Generated by Django 4.2.25 on 2025-10-18 21:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('license_number', models.CharField(max_length=64, unique=True)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color_hex', models.CharField(default='#2563eb', max_length=7)),
                ('encoded_polyline', models.TextField(blank=True)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('average_travel_minutes', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('callsign', models.CharField(max_length=50, unique=True)),
                ('vin', models.CharField(max_length=32, unique=True)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], default='active', max_length=32)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('telematics_device_id', models.CharField(max_length=64, unique=True)),
                ('last_known_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_known_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_reported_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['callsign'],
            },
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tracking.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tracking.vehicle')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleJourney',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_arrival_at', models.DateTimeField(blank=True, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('average_speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('driver_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journeys', to='tracking.vehicleassignment')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journeys', to='tracking.route')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='tracking.vehicle')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TrafficSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=255)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('features', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['captured_at'], name='tracking_tr_capture_3fbcc8_idx')],
            },
        ),
        migrations.CreateModel(
            name='RouteLeg',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence_no', models.PositiveIntegerField()),
                ('origin_label', models.CharField(max_length=255)),
                ('origin_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('origin_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_label', models.CharField(max_length=255)),
                ('destination_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='tracking.route')),
            ],
            options={
                'ordering': ['route', 'sequence_no'],
            },
        ),
        migrations.CreateModel(
            name='LocationPing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('heading_deg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('satellite_count', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pings', to='tracking.vehiclejourney')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vehiclejourney',
            index=models.Index(fields=['vehicle', 'started_at'], name='tracking_ve_vehicle_2c3423_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclejourney',
            index=models.Index(fields=['status'], name='tracking_ve_status_9f3d5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('vehicle',), name='uniq_vehicle_active_assignment'),
        ),
        migrations.AddConstraint(
            model_name='vehicleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('driver',), name='uniq_driver_active_assignment'),
        ),
        migrations.AlterUniqueTogether(
            name='routeleg',
            unique_together={('route', 'sequence_no')},
        ),
        migrations.AddIndex(
            model_name='locationping',
            index=models.Index(fields=['journey', 'recorded_at'], name='tracking_lo_journey_f9582b_idx'),
        ),
        migrations.AddIndex(
            model_name='locationping',
            index=models.Index(fields=['recorded_at'], name='tracking_lo_recorde_6b6e30_idx'),
        ),
    ]
