# Generated by Django 4.2.25 on 2025-11-03 15:19

from django.db import migrations


def seed_initial_vehicles(apps, schema_editor):
    Vehicle = apps.get_model('tracking', 'Vehicle')
    initial_vehicles = [
        # 3 En Route Vehicles
        {'name': 'Truck A', 'license_plate': 'DHK-101', 'vin': 'VIN001', 'make': 'Ford', 'model': 'Transit', 'year': 2022, 'status': 'en_route', 'latitude': 23.7949, 'longitude': 90.4142},
        {'name': 'Van B', 'license_plate': 'DHK-102', 'vin': 'VIN002', 'make': 'Toyota', 'model': 'Hiace', 'year': 2021, 'status': 'en_route', 'latitude': 23.7508, 'longitude': 90.3932},
        {'name': 'Truck C', 'license_plate': 'DHK-103', 'vin': 'VIN003', 'make': 'Mercedes', 'model': 'Sprinter', 'year': 2023, 'status': 'en_route', 'latitude': 23.7340, 'longitude': 90.4125},
        # 2 Idle Vehicles
        {'name': 'Truck D', 'license_plate': 'DHK-104', 'vin': 'VIN004', 'make': 'Ford', 'model': 'Transit', 'year': 2022, 'status': 'idle', 'latitude': 23.874, 'longitude': 90.398},
        {'name': 'Van E', 'license_plate': 'DHK-105', 'vin': 'VIN005', 'make': 'Toyota', 'model': 'Hiace', 'year': 2021, 'status': 'idle', 'latitude': 23.766, 'longitude': 90.400},
        # 1 Maintenance Vehicle
        {'name': 'Truck F', 'license_plate': 'DHK-106', 'vin': 'VIN006', 'make': 'Mercedes', 'model': 'Sprinter', 'year': 2020, 'status': 'maintenance', 'latitude': 23.766, 'longitude': 90.400},
    ]

    for v_data in initial_vehicles:
        Vehicle.objects.get_or_create(vin=v_data['vin'], defaults=v_data)

class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_vehicle_latitude_vehicle_longitude_vehicle_status'),
    ]

    operations = [
        migrations.RunPython(seed_initial_vehicles),
    ]
