# Generated by Django 4.2.25 on 2025-11-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_seed_initial_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
