# Generated by Django 4.2.25 on 2025-11-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_vehicle_driver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver_license',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
